### ISSUE TITLE
Error on mvn import-feature for ServerDC

### ISSUE THREAD

**Issue by jpyperez** [Xray-App/xray-maven-plugin#62]
Hello,

I'm facing an error when new scenarios are send to jira.
Note:
- This error doesn't happen to update the existing scenarios
- This error doesn't happen for only one new scenario

When I call `mvn mvn xray:import-features -D"xray.inputFeatures"=my.feature -X` I am receiving this error:
```
java.io.IOException: Unexpected HTTP code Response{protocol=http/1.1, code=500, message=, url=https://jira.sp.vodafone.com/rest/raven/2.0/import/feature?projectKey=IT&updateRepository=false}
        at app.getxray.xray.XrayFeaturesImporter.importServerDC(XrayFeaturesImporter.java:340)
        at app.getxray.xray.XrayFeaturesImporter.importFrom(XrayFeaturesImporter.java:241)
        at app.getxray.maven.plugin.xray.ImportFeaturesMojo.execute(ImportFeaturesMojo.java:171)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
```

This is part of debug:
```
[DEBUG] REQUEST_URL: https://company.com/rest/raven/2.0/import/feature?projectKey=IT&updateRepository=false
[DEBUG] REQUEST_METHOD: POST
[DEBUG] REQUEST_CONTENT_TYPE: multipart/form-data; boundary=61e3637e-6d33-459f-ad53-5bab17c09880
[DEBUG] RESPONSE_CONTENT_TYPE:application/json;charset=UTF-8
[DEBUG] RESPONSE_HTTP_STATUS: 500
[DEBUG] RESPONSE_BODY:
[DEBUG] =======================
[DEBUG] java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.b(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.b(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.rest.api.v1.test.a.b.a(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor13969.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper$ResponseOutInvoker.lambda$_dispatch$0(DispatchProviderHelper.java:181)
```

Thanks

**Comment by jpyperez** [comment]
Hey,

I tried to run using curl, and I'm receiving the same "No value present" message:
```
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.b(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.b(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.testimport.service.impl.TestImportServiceImpl.a(Unknown Source)
        at com.xpandit.raven.rest.api.v1.test.a.b.a(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor13969.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper$ResponseOutInvoker.lambda$_dispatch$0(DispatchProviderHelper.java:181)
        at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper.lambda$invokeMethodWithInterceptors$0(DispatchProviderHelper.java:81)
        at com.atlassian.plugins.rest.common.interceptor.impl.DefaultMethodInvocation.invoke(DefaultMethodInvocation.java:53)
        at com.atlassian.plugins.rest.common.expand.interceptor.ExpandInterceptor.intercept(ExpandInterceptor.java:42)
        at com.atlassian.plugins.rest.common.interceptor.impl.DefaultMethodInvocation.invoke(DefaultMethodInvocation.java:53)
        at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper.invokeMethodWithInterceptors(DispatchProviderHelper.java:106)
        at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper$ResponseOutInvoker._dispatch(DispatchProviderHelper.java:180)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:171)
        at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:829)
        at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:75)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:62)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:56)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:44)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:62)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.lambda$doFilter$0(DelegatingPluginFilter.java:57)
        at com.atlassian.plugins.rest.module.servlet.RestServletUtilsUpdaterFilter.doFilterInternal(RestServletUtilsUpdaterFilter.java:23)
        at com.atlassian.plugins.rest.module.servlet.RestServletUtilsUpdaterFilter.doFilter(RestServletUtilsUpdaterFilter.java:35)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:62)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.lambda$doFilter$0(DelegatingPluginFilter.java:57)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
```

**Comment by jpyperez** [comment]
Making more searches, I think it can be a known error from jira's side .-.
https://community.atlassian.com/t5/Marketplace-Apps-Integrations/Null-pointer-exception-when-importing-feature-file-to-xray/qaq-p/2098977

**Comment by bitcoder** [comment]
Hi @jpyperez , sorry for the late reply. It seems you're getting an error from the server. HTTP error 500 indicates some unexpected error occured on server side.
My recommendation is to use `curl` or similar utility to make the HTTP request to Xray's REST API. If you can replicate the error, as it seems the case, then report it to [Xray support team;](https://jira.getxray.app/servicedesk/customer/portal/2/user/login) it's the correct way to address it and track it.
As this doesn't seem related to the Xray Maven plugin itself, I'll close this issue later on.
Thanks for investigation and please share your findings with the Xray support team.
